//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsApplication.ALBgreedy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeoutFault", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class TimeoutFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ALBgreedy.IGreedyService")]
    public interface IGreedyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreedyService/GreedyAlg", ReplyAction="http://tempuri.org/IGreedyService/GreedyAlgResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AllocationsApplication.ALBgreedy.TimeoutFault), Action="http://tempuri.org/IGreedyService/GreedyAlgTimeoutFaultFault", Name="TimeoutFault", Namespace="http://schemas.datacontract.org/2004/07/")]
        WcfServiceLibrary.AllocationData GreedyAlg(int deadline, WcfServiceLibrary.ConfigData cd, int task);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGreedyService/GreedyAlg", ReplyAction="http://tempuri.org/IGreedyService/GreedyAlgResponse")]
        System.IAsyncResult BeginGreedyAlg(int deadline, WcfServiceLibrary.ConfigData cd, int task, System.AsyncCallback callback, object asyncState);
        
        WcfServiceLibrary.AllocationData EndGreedyAlg(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreedyServiceChannel : AllocationsApplication.ALBgreedy.IGreedyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreedyAlgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GreedyAlgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WcfServiceLibrary.AllocationData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WcfServiceLibrary.AllocationData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreedyServiceClient : System.ServiceModel.ClientBase<AllocationsApplication.ALBgreedy.IGreedyService>, AllocationsApplication.ALBgreedy.IGreedyService {
        
        private BeginOperationDelegate onBeginGreedyAlgDelegate;
        
        private EndOperationDelegate onEndGreedyAlgDelegate;
        
        private System.Threading.SendOrPostCallback onGreedyAlgCompletedDelegate;
        
        public GreedyServiceClient() {
        }
        
        public GreedyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreedyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreedyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreedyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GreedyAlgCompletedEventArgs> GreedyAlgCompleted;
        
        public WcfServiceLibrary.AllocationData GreedyAlg(int deadline, WcfServiceLibrary.ConfigData cd, int task) {
            return base.Channel.GreedyAlg(deadline, cd, task);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGreedyAlg(int deadline, WcfServiceLibrary.ConfigData cd, int task, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGreedyAlg(deadline, cd, task, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WcfServiceLibrary.AllocationData EndGreedyAlg(System.IAsyncResult result) {
            return base.Channel.EndGreedyAlg(result);
        }
        
        private System.IAsyncResult OnBeginGreedyAlg(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int deadline = ((int)(inValues[0]));
            WcfServiceLibrary.ConfigData cd = ((WcfServiceLibrary.ConfigData)(inValues[1]));
            int task = ((int)(inValues[2]));
            return this.BeginGreedyAlg(deadline, cd, task, callback, asyncState);
        }
        
        private object[] OnEndGreedyAlg(System.IAsyncResult result) {
            WcfServiceLibrary.AllocationData retVal = this.EndGreedyAlg(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGreedyAlgCompleted(object state) {
            if ((this.GreedyAlgCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GreedyAlgCompleted(this, new GreedyAlgCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GreedyAlgAsync(int deadline, WcfServiceLibrary.ConfigData cd, int task) {
            this.GreedyAlgAsync(deadline, cd, task, null);
        }
        
        public void GreedyAlgAsync(int deadline, WcfServiceLibrary.ConfigData cd, int task, object userState) {
            if ((this.onBeginGreedyAlgDelegate == null)) {
                this.onBeginGreedyAlgDelegate = new BeginOperationDelegate(this.OnBeginGreedyAlg);
            }
            if ((this.onEndGreedyAlgDelegate == null)) {
                this.onEndGreedyAlgDelegate = new EndOperationDelegate(this.OnEndGreedyAlg);
            }
            if ((this.onGreedyAlgCompletedDelegate == null)) {
                this.onGreedyAlgCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGreedyAlgCompleted);
            }
            base.InvokeAsync(this.onBeginGreedyAlgDelegate, new object[] {
                        deadline,
                        cd,
                        task}, this.onEndGreedyAlgDelegate, this.onGreedyAlgCompletedDelegate, userState);
        }
    }
}
